version: '{build}'
shallow_clone: true

platform: x64
configuration:
  - Debug
  - Release

environment:
  MSBUILD_FLAGS: /verbosity:normal /maxcpucount
  matrix:
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019

matrix:
  fast_finish: false

before_build:
  - git config --global user.email "ci@appveyor.com"
  - git config --global user.name "CI"
  - where dotnet
  - dotnet --info
  - cmake --version
  - cmake -S. -Bbuild -G "Visual Studio 16 2019" -DCMAKE_BUILD_TYPE=%configuration%

build_script:
  - cmake --build build --config %configuration% --target ALL_BUILD -- %MSBUILD_FLAGS%

test_script:
  - cmake --build build --config %configuration% --target RUN_TESTS -- %MSBUILD_FLAGS%
