version: '{build}'
shallow_clone: true

platform: x64

environment:
  MSBUILD_FLAGS: /verbosity:minimal /maxcpucount
  matrix:
# Makefile
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    VS: 2017

  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    VS: 2015

matrix:
  fast_finish: false

before_build:
  - git config --global user.email "ci@appveyor.com"
  - git config --global user.name "CI"
  - if "%VS%"=="2017" call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
  - if "%VS%"=="2015" call "C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x64
  - if "%VS%"=="2015" call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86_amd64
  - where dotnet
  - dotnet --info

build_script:
  - dotnet build --runtime win-x64 src\FooApp\FooApp.csproj

test_script:
  - dotnet dotnet src\FooApp\bin\x64\Debug\netcoreapp2.1\win-x64\Mizux.FooApp.dll

