language: cpp

matrix:
  include:
# Makefile builder
    - os: linux
      dist: xenial
      compiler: gcc
    - os: osx
      osx_image: xode9.4
      compiler: clang

install:
  - ./.travis/install.sh

script:
  - ./.travis/script.sh
